{"name": "Invalid login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B6F83E]\n\t(No symbol) [0x00C0454E]\n\t(No symbol) [0x00C1EA19]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I open the browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.89)\nStacktrace:\n\tGetHandleVerifier [0x00D2B5A3+24387]\n\t(No symbol) [0x00CB5904]\n\t(No symbol) [0x00B90753]\n\t(No symbol) [0x00B6F83E]\n\t(No symbol) [0x00C0454E]\n\t(No symbol) [0x00C1EA19]\n\t(No symbol) [0x00BFD646]\n\t(No symbol) [0x00BCC59F]\n\t(No symbol) [0x00BCD8E4]\n\tGetHandleVerifier [0x0102D883+3179043]\n\tGetHandleVerifier [0x01046CF9+3282585]\n\tGetHandleVerifier [0x0104167C+3260444]\n\tGetHandleVerifier [0x00DC4330+650448]\n\t(No symbol) [0x00CBED0D]\n\t(No symbol) [0x00CBBAF8]\n\t(No symbol) [0x00CBBC99]\n\t(No symbol) [0x00CAE530]\n\tBaseThreadInitThunk [0x766A5D49+25]\n\tRtlInitializeExceptionChain [0x7753CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7753CDC1+561]\n\n", "trace": "  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\example_steps.py\", line 8, in step_open_browser\n    context.driver.get(\"https://practicetestautomation.com/practice-test-login/\")\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 454, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mike Redondo\\OneDrive\\Desktop\\asdasdas\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742202996855, "stop": 1742202996892}, {"name": "When I enter the username \"student\"", "status": "skipped", "start": 1742202996895, "stop": 1742202996895}, {"name": "And I enter the password \"Password123\"", "status": "skipped", "start": 1742202996895, "stop": 1742202996895}, {"name": "And I click the login button", "status": "skipped", "start": 1742202996895, "stop": 1742202996895}, {"name": "Then I should see the success message \"Invalid login\"", "status": "skipped", "start": 1742202996895, "stop": 1742202996895}], "start": 1742202996853, "stop": 1742202996895, "uuid": "d8b9ada5-a867-42e4-a696-60b4de823fe7", "historyId": "35890fcf46fa3dcb90b7287fed59418a", "fullName": "Login and Navigate to Pages: Invalid login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login and Navigate to Pages"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}